In [5]:
!pip3 install keras --user
!pip3 install tensorflow --user

pyspark 2.4.0 requires py4j==0.10.7, which is not installed.
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pyspark 2.4.0 requires py4j==0.10.7, which is not installed.
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [2]:
training_data = pd.read_csv("train.csv")
testing_data = pd.read_csv("test.csv")
costa_rica_data = training_data.drop(['Target'], axis=1)
costa_rica_target = training_data['Target']

In [3]:
costa_rica_data = costa_rica_data.select_dtypes(include=[np.number], exclude=[np.object]).fillna(0)
costa_rica_data = StandardScaler().fit_transform(costa_rica_data)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(costa_rica_data, costa_rica_target, test_size=0.3)

In [9]:
X_train.shape

(6689, 137)

In [8]:
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense

Using TensorFlow backend.


### Iteration 1

In [13]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(66, activation='relu', kernel_initializer='random_normal', input_dim=137))

#Second  Hidden Layer
classifier.add(Dense(66, activation='relu', kernel_initializer='random_normal'))

#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [14]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [15]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=10, epochs=100)

Epoch 1/100
6689/6689 [==============================] - 1s 188us/step - loss: -33.5358 - acc: 0.0783
Epoch 2/100
6689/6689 [==============================] - 1s 139us/step - loss: -36.7695 - acc: 0.0785
Epoch 3/100
6689/6689 [==============================] - 1s 160us/step - loss: -36.7755 - acc: 0.0785
Epoch 4/100
6689/6689 [==============================] - 1s 145us/step - loss: -36.7755 - acc: 0.0785
Epoch 5/100
6689/6689 [==============================] - 1s 142us/step - loss: -36.7755 - acc: 0.0785
Epoch 6/100
6689/6689 [==============================] - 1s 140us/step - loss: -36.7755 - acc: 0.0785
Epoch 7/100
6689/6689 [==============================] - 1s 140us/step - loss: -36.7755 - acc: 0.0785
Epoch 8/100
6689/6689 [==============================] - 1s 147us/step - loss: -36.7755 - acc: 0.0785
Epoch 9/100
6689/6689 [==============================] - 1s 141us/step - loss: -36.7755 - acc: 0.0785
Epoch 10/100
6689/6689 [==============================] - 1s 139us/step - loss: -3

In [16]:
eval_model=classifier.evaluate(X_train, y_train)
eval_model

6689/6689 [==============================] - 0s 26us/step


[-36.775451086155236, 0.078487068321124231]

In [17]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 230    0    0    0]
 [ 480    0    0    0]
 [ 381    0    0    0]
 [1777    0    0    0]]


### Iteration 2

In [28]:
classifier2 = Sequential()
#First Hidden Layer
classifier2.add(Dense(66, activation='relu', kernel_initializer='random_normal', input_dim=137))

#Second  Hidden Layer
classifier2.add(Dense(66, activation='relu', kernel_initializer='random_normal'))

#Output Layer
classifier2.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [29]:
#Compiling the neural network
classifier2.compile(optimizer ='sgd',loss='binary_crossentropy', metrics =['accuracy'])

In [30]:
#Fitting the data to the training dataset
classifier2.fit(X_test,y_test, batch_size=10, epochs=100)

Epoch 1/100
2868/2868 [==============================] - 0s 165us/step - loss: -31.6966 - acc: 0.0802
Epoch 2/100
2868/2868 [==============================] - 0s 129us/step - loss: -36.5374 - acc: 0.0802
Epoch 3/100
2868/2868 [==============================] - 0s 131us/step - loss: -36.5374 - acc: 0.0802
Epoch 4/100
2868/2868 [==============================] - 0s 129us/step - loss: -36.5374 - acc: 0.0802
Epoch 5/100
2868/2868 [==============================] - 0s 147us/step - loss: -36.5374 - acc: 0.0802
Epoch 6/100
2868/2868 [==============================] - 0s 128us/step - loss: -36.5374 - acc: 0.0802
Epoch 7/100
2868/2868 [==============================] - 0s 130us/step - loss: -36.5374 - acc: 0.0802
Epoch 8/100
2868/2868 [==============================] - 0s 135us/step - loss: -36.5374 - acc: 0.0802
Epoch 9/100
2868/2868 [==============================] - 0s 165us/step - loss: -36.5374 - acc: 0.0802
Epoch 10/100
2868/2868 [==============================] - 0s 131us/step - loss: -3

In [31]:
eval_model=classifier2.evaluate(X_test, y_test)
eval_model

2868/2868 [==============================] - 0s 35us/step


[-36.537410475386402, 0.08019525806109111]

In [35]:
y_pred2=classifier2.predict(X_test)
y_pred2 =(y_pred>0.5)

In [36]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)

[[ 230    0    0    0]
 [ 480    0    0    0]
 [ 381    0    0    0]
 [1777    0    0    0]]


### Iteration 3

In [47]:
classifier3 = Sequential()
#First Hidden Layer
classifier3.add(Dense(100, activation='relu', kernel_initializer='random_normal', input_dim=137))

#Second  Hidden Layer
classifier3.add(Dense(80, activation='relu', kernel_initializer='random_normal'))

#Third  Hidden Layer
classifier3.add(Dense(60, activation='relu', kernel_initializer='random_normal'))

#Fourth  Hidden Layer
classifier3.add(Dense(60, activation='relu', kernel_initializer='random_normal'))

#Fifth  Hidden Layer
classifier3.add(Dense(40, activation='relu', kernel_initializer='random_normal'))

#Sixth  Hidden Layer
classifier3.add(Dense(20, activation='relu', kernel_initializer='random_normal'))

#Seventh  Hidden Layer
classifier3.add(Dense(20, activation='relu', kernel_initializer='random_normal'))

#Output Layer
classifier3.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [48]:
#Compiling the neural network
classifier3.compile(optimizer ='adagrad',loss='binary_crossentropy', metrics =['accuracy'])

In [49]:
#Fitting the data to the training dataset
classifier3.fit(X_test,y_test, batch_size=10, epochs=10)

Epoch 1/100
2868/2868 [==============================] - 1s 247us/step - loss: -35.8546 - acc: 0.0802
Epoch 2/100
2868/2868 [==============================] - 0s 171us/step - loss: -36.5374 - acc: 0.0802
Epoch 3/100
2868/2868 [==============================] - 0s 171us/step - loss: -36.5374 - acc: 0.0802
Epoch 4/100
2868/2868 [==============================] - 1s 175us/step - loss: -36.5374 - acc: 0.0802
Epoch 5/100
2868/2868 [==============================] - 1s 184us/step - loss: -36.5374 - acc: 0.0802
Epoch 6/100
2868/2868 [==============================] - 1s 177us/step - loss: -36.5374 - acc: 0.0802
Epoch 7/100
2868/2868 [==============================] - 1s 186us/step - loss: -36.5374 - acc: 0.0802
Epoch 8/100
2868/2868 [==============================] - 0s 172us/step - loss: -36.5374 - acc: 0.0802
Epoch 9/100
2868/2868 [==============================] - 0s 169us/step - loss: -36.5374 - acc: 0.0802
Epoch 10/100
2868/2868 [==============================] - 0s 173us/step - loss: -3

In [50]:
eval_model=classifier3.evaluate(X_test, y_test)
eval_model

2868/2868 [==============================] - 0s 52us/step


[-36.537410475386402, 0.08019525806109111]

In [51]:
y_pred3=classifier2.predict(X_test)
y_pred3 =(y_pred>0.5)

In [52]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)

[[ 230    0    0    0]
 [ 480    0    0    0]
 [ 381    0    0    0]
 [1777    0    0    0]]
